### ISSUE TITLE
LocalStack with Docker Desktop wont start

### ISSUE THREAD

**Issue by pramineni01** [localstack/localstack-docker-extension#34]
LocalStack with Docker Desktop wont start

Env:
Tried on 2 Macbook Pros (Apple chip and Intel chip)
Steps to reproduce:

Installed localstack extension for Docker Desktop.
2.Clicked on Start. And am seeing the error below:
2023-04-19T04:34:20.538 INFO --- [-functhread1] localstack.utils.threads : Thread run method <function Server.do_start_thread.._run at 0xffff8a4683a0>(None) failed: Traceback (most recent call last): File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/api/client.py", line 268, in _raise_for_status response.raise_for_status() File "/opt/code/localstack/.venv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.41/containers/create?name=localstack_main The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/opt/code/localstack/localstack/utils/container_utils/docker_sdk_client.py", line 613, in create_container container = create_container() File "/opt/code/localstack/localstack/utils/container_utils/docker_sdk_client.py", line 594, in create_container return self.client().containers.create( File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/models/containers.py", line 906, in create resp = self.client.api.create_container(**create_kwargs) File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/api/container.py", line 431, in create_container return self.create_container_from_config(config, name, platform) File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/api/container.py", line 448, in create_container_from_config return self._result(res, True) File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/api/client.py", line 274, in _result self._raise_for_status(response) File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/api/client.py", line 270, in _raise_for_status raise create_api_error_from_http_exception(e) from e File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception raise cls(e, response=response, explanation=explanation) from e docker.errors.APIError: 409 Client Error for http+docker://localhost/v1.41/containers/create?name=localstack_main: Conflict ("Conflict. The container name "/localstack_main" is already in use by container "9d65f950461eeb8a86b986ef8626392372b66c82d36cd5cfc12baa64af18099a". You have to remove (or rename) that container to be able to reuse that name.") The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/opt/code/localstack/localstack/utils/threads.py", line 58, in run result = self.func(self.params, **kwargs) File "/opt/code/localstack/localstack/utils/serving.py", line 168, in _run return self.do_run() File "/opt/code/localstack/localstack/utils/bootstrap.py", line 475, in do_run return self.container.run() File "/opt/code/localstack/localstack/utils/bootstrap.py", line 407, in run return DOCKER_CLIENT.run_container( File "/opt/code/localstack/localstack/utils/container_utils/docker_sdk_client.py", line 661, in run_container container = self.create_container( File "/opt/code/localstack/localstack/utils/container_utils/docker_sdk_client.py", line 621, in create_container raise ContainerException() from e localstack.utils.container_utils.container_client.ContainerException
/

**Comment by Pive01** [comment]
Hi @pramineni01 , It seems that you already have a container named "localstack_main" that is running; if you don't see other containers try going to Settings > Extensions > Show Docker Extensions system containers
